apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - nfsvers=4.1
  nfs:
    path: /nfs_data
    server: nfs-server
