apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fe
  template:
    metadata:
      labels:
        app: fe
    spec:
      containers:
        - name: fe
          image: shekeriev/k8s-facts-fe
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: fe-cm
