apiVersion: v1
kind: Pod
metadata:
  name: env
  labels:
    app: hw
spec:
  containers:
    - name: homework
      image: shekeriev/k8s-environ
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /config
          name: main-conf-volume
        - mountPath: /secret
          name: secret-conf-volume
      envFrom:
        - configMapRef:
            name: hwcm
          prefix: HW_ # Use this to prefix variables created from the ConfigMap
      env:
        - name: HW_PORT
          valueFrom:
            secretKeyRef:
              name: hwsec
              key: port
  volumes:
    - name: main-conf-volume
      hostPath:
        path: /home/vagrant/config
    - name: secret-conf-volume
      hostPath:
        path: /home/vagrant/secret/

---
apiVersion: v1
kind: Service
metadata:
  name: env-svc
  labels:
    app: hw
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30001
  selector:
    app: hw
