apiVersion: v1
kind: LimitRange
metadata:
  name: limits
  namespace: projectx
spec:
  limits:
  - type: Container
    max:
      cpu: 250m
      memory: 200Mi
    min:
      cpu: 50m
      memory: 50Mi
    default:
      cpu: 100m
      memory: 100Mi
    defaultRequest:
      cpu: 50m
      memory: 50Mi
