apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: projectx
spec:
  hard:
    pods: 10
    services: 5
    replicationcontrollers: 5
    requests.cpu: 1
    requests.memory: 1Gi
    limits.cpu: 2
    limits.memory: 2Gi