apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: devguru
  namespace: projectx
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - create
  - delete
  - update
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - create
  - delete
  - update
  - watch
  - patch
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
  - list
  - create
  - delete
  - update
  - watch
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - create
  - delete
  - update
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devguru
  namespace: projectx
subjects:
- kind: User
  name: ivan
- kind: User
  name: mariana
- kind: Group
  name: gurus 
roleRef:
  kind: Role
  name: devguru
  apiGroup: rbac.authorization.k8s.io
