apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}-svc
spec:
  ports:
  - port: 80
    nodePort: {{ .Values.nodePort | default 31000 }}
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Release.Name }}
  type: NodePort